server:
  port: 8888

#logging:
#  level: debug

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/practice
    username: root
    password: 1234
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      connection-timeout: 30000
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
